#!/usr/bin/env bun

/**
 * Migration Execution Script
 *
 * This script executes the Clerk → Custom Auth migration by sending migration emails to users.
 *
 * What it does:
 * 1. Reads migration plan from CSV (generated by plan-migration.ts)
 * 2. For each active user:
 *    - Generates migration token (7-day expiry)
 *    - Hashes and stores in password_resets table
 *    - Schedules sendMigrationEmail action
 * 3. Rate limits to 1000 emails/hour (Resend limit)
 * 4. Logs progress to file
 * 5. Idempotent: skips users who already have migration tokens
 * 6. Can resume from last batch if interrupted
 *
 * Usage:
 *   bun scripts/execute-migration.ts [options]
 *
 * Options:
 *   --dry-run           : Show what would happen without sending emails
 *   --batch-size N      : Override batch size (default: 1000)
 *   --resume            : Resume from last checkpoint
 *   --start-from N      : Start from specific user index
 *   --limit N           : Process only N users (for testing)
 *
 * Examples:
 *   bun scripts/execute-migration.ts --dry-run
 *   bun scripts/execute-migration.ts --limit 10
 *   bun scripts/execute-migration.ts --resume
 *   bun scripts/execute-migration.ts
 */

import { ConvexHttpClient } from 'convex/browser';
import { api } from '../convex/_generated/api';
import fs from 'fs';
import path from 'path';
import { parse } from 'csv-parse/sync';

// Initialize Convex client
const CONVEX_URL = process.env.NEXT_PUBLIC_CONVEX_URL;

if (!CONVEX_URL) {
  console.error('❌ Error: NEXT_PUBLIC_CONVEX_URL not set');
  process.exit(1);
}

const client = new ConvexHttpClient(CONVEX_URL);

interface MigrationUser {
  memberId: string;
  email: string;
  clerkId: string;
  firstName: string;
  lastName: string;
  status: string;
  emailVerified: string;
  migrationStatus: string;
}

interface MigrationProgress {
  startedAt: string;
  lastProcessedIndex: number;
  totalProcessed: number;
  totalSkipped: number;
  totalFailed: number;
  emailsSent: number;
  currentBatch: number;
  checkpoints: Array<{
    timestamp: string;
    index: number;
    processed: number;
  }>;
}

interface CommandLineArgs {
  dryRun: boolean;
  batchSize: number;
  resume: boolean;
  startFrom: number;
  limit?: number;
}

// Parse command line arguments
function parseArgs(): CommandLineArgs {
  const args = process.argv.slice(2);
  const parsed: CommandLineArgs = {
    dryRun: args.includes('--dry-run'),
    batchSize: 1000,
    resume: args.includes('--resume'),
    startFrom: 0,
  };

  // Parse batch size
  const batchSizeIndex = args.indexOf('--batch-size');
  if (batchSizeIndex !== -1 && args[batchSizeIndex + 1]) {
    parsed.batchSize = parseInt(args[batchSizeIndex + 1], 10);
  }

  // Parse start from
  const startFromIndex = args.indexOf('--start-from');
  if (startFromIndex !== -1 && args[startFromIndex + 1]) {
    parsed.startFrom = parseInt(args[startFromIndex + 1], 10);
  }

  // Parse limit
  const limitIndex = args.indexOf('--limit');
  if (limitIndex !== -1 && args[limitIndex + 1]) {
    parsed.limit = parseInt(args[limitIndex + 1], 10);
  }

  return parsed;
}

// Load migration plan from CSV
function loadMigrationPlan(): MigrationUser[] {
  const csvPath = path.join(process.cwd(), 'migration-data', 'migration-plan.csv');

  if (!fs.existsSync(csvPath)) {
    console.error('❌ Error: Migration plan not found');
    console.error('Please run: bun scripts/plan-migration.ts');
    process.exit(1);
  }

  const csvContent = fs.readFileSync(csvPath, 'utf-8');
  const records = parse(csvContent, {
    columns: true,
    skip_empty_lines: true,
  });

  return records.filter((user: MigrationUser) => user.migrationStatus === 'pending');
}

// Load or create progress file
function loadProgress(): MigrationProgress {
  const progressPath = path.join(process.cwd(), 'migration-data', 'migration-progress.json');

  if (fs.existsSync(progressPath)) {
    return JSON.parse(fs.readFileSync(progressPath, 'utf-8'));
  }

  return {
    startedAt: new Date().toISOString(),
    lastProcessedIndex: -1,
    totalProcessed: 0,
    totalSkipped: 0,
    totalFailed: 0,
    emailsSent: 0,
    currentBatch: 1,
    checkpoints: [],
  };
}

// Save progress
function saveProgress(progress: MigrationProgress): void {
  const progressPath = path.join(process.cwd(), 'migration-data', 'migration-progress.json');
  fs.writeFileSync(progressPath, JSON.stringify(progress, null, 2));
}

// Create checkpoint
function createCheckpoint(progress: MigrationProgress, index: number): void {
  progress.checkpoints.push({
    timestamp: new Date().toISOString(),
    index,
    processed: progress.totalProcessed,
  });

  saveProgress(progress);

  console.log(`💾 Checkpoint saved at index ${index} (${progress.totalProcessed} processed)`);
}

// Log migration event
function logEvent(message: string, level: 'info' | 'warn' | 'error' = 'info'): void {
  const timestamp = new Date().toISOString();
  const logPath = path.join(process.cwd(), 'migration-data', 'migration.log');
  const logMessage = `[${timestamp}] [${level.toUpperCase()}] ${message}\n`;

  fs.appendFileSync(logPath, logMessage);

  const emoji = level === 'error' ? '❌' : level === 'warn' ? '⚠️' : 'ℹ️';
  console.log(`${emoji} ${message}`);
}

// Send migration email for a single user
async function sendMigrationEmail(
  user: MigrationUser,
  dryRun: boolean
): Promise<{ success: boolean; error?: string }> {
  try {
    if (dryRun) {
      console.log(`   [DRY RUN] Would send migration email to: ${user.email}`);
      return { success: true };
    }

    // Call Convex mutation to create migration token and send email
    // Note: This assumes there's a mutation for creating migration tokens
    await client.mutation(api.auth.createMigrationToken as any, {
      memberId: user.memberId,
      email: user.email,
      firstName: user.firstName,
      lastName: user.lastName,
    });

    return { success: true };
  } catch (error) {
    const errorMessage = error instanceof Error ? error.message : String(error);
    return { success: false, error: errorMessage };
  }
}

// Delay to respect rate limit (1000 emails/hour = 3.6 seconds per email)
async function rateLimit(emailsSent: number, batchSize: number): Promise<void> {
  const emailsPerHour = batchSize;
  const msPerEmail = (3600 * 1000) / emailsPerHour; // Convert to milliseconds

  await new Promise((resolve) => setTimeout(resolve, msPerEmail));
}

// Execute migration
async function executeMigration(args: CommandLineArgs): Promise<void> {
  console.log('🚀 Starting migration execution...\n');

  if (args.dryRun) {
    console.log('🔍 DRY RUN MODE - No emails will be sent\n');
  }

  // Load migration plan
  const users = loadMigrationPlan();
  console.log(`📋 Loaded ${users.length} users to migrate\n`);

  if (users.length === 0) {
    console.log('✅ No users to migrate');
    return;
  }

  // Load progress
  let progress = loadProgress();

  // Handle resume
  let startIndex = args.startFrom;
  if (args.resume && progress.lastProcessedIndex >= 0) {
    startIndex = progress.lastProcessedIndex + 1;
    console.log(`📍 Resuming from index ${startIndex}\n`);
  }

  // Apply limit if specified
  const endIndex = args.limit ? Math.min(startIndex + args.limit, users.length) : users.length;
  const usersToProcess = users.slice(startIndex, endIndex);

  console.log(`📊 Processing ${usersToProcess.length} users (index ${startIndex} to ${endIndex - 1})\n`);

  // Process users
  for (let i = 0; i < usersToProcess.length; i++) {
    const globalIndex = startIndex + i;
    const user = usersToProcess[i];

    console.log(`\n[${globalIndex + 1}/${users.length}] Processing: ${user.email}`);

    // Send migration email
    const result = await sendMigrationEmail(user, args.dryRun);

    if (result.success) {
      progress.totalProcessed++;
      progress.emailsSent++;
      console.log(`   ✅ Email sent successfully`);
      logEvent(`Migration email sent to ${user.email} (${user.memberId})`);
    } else {
      progress.totalFailed++;
      console.log(`   ❌ Failed: ${result.error}`);
      logEvent(`Failed to send migration email to ${user.email}: ${result.error}`, 'error');
    }

    progress.lastProcessedIndex = globalIndex;

    // Save checkpoint every 100 users
    if ((i + 1) % 100 === 0) {
      createCheckpoint(progress, globalIndex);
    }

    // Rate limit
    if (!args.dryRun) {
      await rateLimit(progress.emailsSent, args.batchSize);
    }
  }

  // Final save
  saveProgress(progress);

  // Print summary
  console.log('\n' + '='.repeat(60));
  console.log('📊 MIGRATION EXECUTION SUMMARY');
  console.log('='.repeat(60));
  console.log(`\nTotal processed:  ${progress.totalProcessed}`);
  console.log(`Emails sent:      ${progress.emailsSent}`);
  console.log(`Failed:           ${progress.totalFailed}`);
  console.log(`Skipped:          ${progress.totalSkipped}`);
  console.log(`\nLast index:       ${progress.lastProcessedIndex}`);
  console.log(`Current batch:    ${progress.currentBatch}`);

  if (args.dryRun) {
    console.log('\n🔍 DRY RUN COMPLETE - No emails were actually sent');
    console.log('Run without --dry-run to execute migration');
  } else {
    console.log('\n✅ Migration execution complete!');
  }

  console.log('\n📁 Output files:');
  console.log('   migration-data/migration-progress.json - Progress tracking');
  console.log('   migration-data/migration.log           - Detailed logs');

  if (progress.lastProcessedIndex < users.length - 1) {
    console.log('\n🔄 To resume migration, run:');
    console.log('   bun scripts/execute-migration.ts --resume');
  }

  console.log('\n' + '='.repeat(60) + '\n');
}

// Main execution
async function main() {
  try {
    const args = parseArgs();
    await executeMigration(args);
    process.exit(0);
  } catch (error) {
    console.error('\n❌ Migration execution failed:', error);
    logEvent(`Migration execution failed: ${error}`, 'error');
    process.exit(1);
  }
}

main();
